# Generated by Django 4.2.11 on 2024-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdata',
            name='functionNM',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
