# Generated by Django 4.2.11 on 2024-05-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_ipdata_functionnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNM', models.CharField(blank=True, max_length=128)),
                ('secondNM', models.CharField(blank=True, max_length=128)),
                ('age', models.CharField(blank=True, max_length=128)),
                ('rightData', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
