# Generated by Django 4.2.13 on 2024-07-06 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDivType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=128)),
                ('shortText', models.CharField(max_length=128)),
                ('fullText', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=128)),
                ('shortText', models.CharField(max_length=128)),
                ('fullText', models.TextField(blank=True, null=True)),
                ('averagePrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='orders_images')),
                ('subDivType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.subdivtype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('orderPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.ordertype')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordertype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
