# Generated by Django 4.2.13 on 2024-07-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
