# Generated by Django 4.2.13 on 2024-06-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstUserLogin', models.CharField(blank=True, max_length=40)),
                ('secondUserLogin', models.CharField(blank=True, max_length=40)),
                ('firstUserName', models.CharField(blank=True, max_length=40)),
                ('secondUserName', models.CharField(blank=True, max_length=40)),
                ('visibility', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chatId', models.IntegerField(default=0)),
                ('ownerLogin', models.CharField(blank=True, max_length=40)),
                ('data', models.FileField(blank=True, upload_to='messages/')),
                ('visibility', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessID', models.IntegerField(default=1)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('firstNM', models.CharField(blank=True, max_length=100)),
                ('secondNM', models.CharField(blank=True, max_length=100)),
                ('thirdNM', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=40)),
                ('userRole', models.CharField(blank=True, max_length=40)),
                ('userType', models.CharField(blank=True, max_length=40)),
                ('fileData', models.FileField(blank=True, upload_to='fileData/')),
                ('urlComm', models.CharField(blank=True, max_length=100)),
                ('fileService', models.FileField(blank=True, upload_to='fileService/')),
                ('urlServ', models.CharField(blank=True, max_length=100)),
                ('fileDroneHub', models.FileField(blank=True, upload_to='fileDroneHub/')),
                ('urlHubs', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('emailRecoveryToken', models.CharField(blank=True, max_length=100)),
                ('directorNM', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('companySite', models.CharField(blank=True, max_length=100)),
                ('mainCity', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('companyName', models.CharField(blank=True, max_length=100)),
                ('inn', models.CharField(blank=True, max_length=100)),
                ('kpp', models.CharField(blank=True, max_length=100)),
                ('ogrn', models.CharField(blank=True, max_length=100)),
                ('legalAddress', models.CharField(blank=True, max_length=1000)),
                ('fullDescription', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
