# Generated by Django 4.2.13 on 2024-07-06 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(default=0)),
                ('notReadFirst', models.IntegerField(default=0)),
                ('notReadSecond', models.IntegerField(default=0)),
                ('firstUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstUser', to=settings.AUTH_USER_MODEL)),
                ('secondUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip4', models.CharField(blank=True, max_length=128)),
                ('ip6', models.CharField(blank=True, max_length=128)),
                ('userName', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('loc', models.CharField(blank=True, max_length=128)),
                ('org', models.CharField(blank=True, max_length=128)),
                ('timezone', models.CharField(blank=True, max_length=128)),
                ('hostname', models.CharField(blank=True, max_length=128)),
                ('functionNM', models.CharField(blank=True, max_length=128)),
                ('language', models.CharField(blank=True, max_length=128)),
                ('date', models.CharField(blank=True, max_length=128)),
                ('data', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTgId', models.BigIntegerField(default=0)),
                ('firstNM', models.CharField(blank=True, max_length=128)),
                ('secondNM', models.CharField(blank=True, max_length=128)),
                ('age', models.CharField(blank=True, max_length=128)),
                ('rightData', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(blank=True, upload_to='messages/')),
                ('visibility', models.IntegerField(default=1)),
                ('notRead', models.IntegerField(default=1)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='users.chat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('walletVolume', models.IntegerField(default=0)),
                ('walletAddress', models.CharField(blank=True, max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
