# Generated by Django 4.2.11 on 2024-05-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='walletVolume',
            field=models.IntegerField(default=0),
        ),
    ]
