# Generated by Django 4.2.13 on 2024-07-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ipdata_tguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='walletAddress',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='walletVolume',
            field=models.IntegerField(default=0),
        ),
    ]
