# Generated by Django 4.2.11 on 2024-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_walletvolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='walletAddress',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
