# Generated by Django 4.2.13 on 2024-07-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('walletVolume', models.IntegerField(default=0)),
                ('walletAddress', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
