# Generated by Django 4.2.13 on 2024-07-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
