# Generated by Django 4.2.13 on 2024-07-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_data_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='firstUserLogin',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='firstUserName',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='notReadFirst',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='notReadSecond',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='secondUserLogin',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='secondUserName',
        ),
    ]
