# Generated by Django 4.2.13 on 2024-07-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_chat_firstuserlogin_remove_chat_firstusername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='notReadFirst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='notReadSecond',
            field=models.IntegerField(default=0),
        ),
    ]
