# Generated by Django 4.2.13 on 2024-07-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_chat_notreadfirst_chat_notreadsecond'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='firstUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
