# Generated by Django 4.2.13 on 2024-07-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_message_ownerlogin_message_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatId',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='users.chat'),
            preserve_default=False,
        ),
    ]
