# Generated by Django 4.2.13 on 2024-06-23 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ggz',
        ),
    ]
