# Generated by Django 4.2.13 on 2024-06-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_ggz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='maxDuration',
            field=models.CharField(blank=True, max_length=2024),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='maxFlightSpeed',
            field=models.CharField(blank=True, max_length=2024),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='maxRangePayload',
            field=models.CharField(blank=True, max_length=2024),
        ),
    ]
