# Generated by Django 4.2.13 on 2024-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_commodity_maxduration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='maxDuration',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='maxFlightSpeed',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='maxRangePayload',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='maxTakeoffWeight',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='dronehub',
            name='article',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='dronehub',
            name='cruisingFlightSpeed',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='dronehub',
            name='maxDuration',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='dronehub',
            name='maxFlightAltitude',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='dronehub',
            name='maxFlightSpeed',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='dronehub',
            name='maxRangePayload',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
        migrations.AlterField(
            model_name='dronehub',
            name='maxTakeoffWeight',
            field=models.CharField(blank=True, default='0', max_length=2024),
        ),
    ]
