version: "3.9"

services:
  back:
    build:
      context: ../backend/militarybet/
      dockerfile: Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_FRONTEND_URL=http://military.shop:8081
      - DJANGO_BACKEND_URL=http://military.shop:8083
    networks:
      - military
    image: "military/back:v1"
    container_name: military_back_v1
    ports:
      - "80:8080"
    volumes:
      - ../backend/militarybet:/usr/src/app

networks:
  military:
    name: military
