version: "3.9"

services:
  back:
    build:
      context: ../backend/militaryanalytics/
      dockerfile: Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_FRONTEND_URL=http://naletay.shop:8081
      - DJANGO_BACKEND_URL=http://naletay.shop:8083
    networks:
      - naletay
    image: "naletay/back:v1"
    container_name: naletay_back_v1
    ports:
      - "80:8080"
    volumes:
      - ../backend/militaryanalytics:/usr/src/app
  nginx:
    build:
      context: ../backend/militaryanalytics/docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    volumes:
      - ./../backend/militaryanalytics/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
     - back
     - front
    ports:
      - "8010:8010"

networks:
  naletay:
    name: naletay
