# Generated by Django 4.2.11 on 2024-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_tguser_usertgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='userTgId',
            field=models.BigIntegerField(default=0),
        ),
    ]
