# Generated by Django 4.2.13 on 2024-06-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='salary_old',
            field=models.IntegerField(default=0),
        ),
    ]
